# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=90)),
                ('ticket_description', models.TextField()),
                ('ticket_time_stamp', models.DateTimeField()),
            ],
        ),
    ]
